project:
  type: website
  output-dir: docs

website:
  title: "Energy Systems Analysis"
  description: "An open course on energy systems analysis developed by Dr. Gang He, covering topics including: energy systems overview; make sense of energy numbers; energy project economics; energy sources and technologies; energy demand; energy, environment, and human health; energy and climate change; power system analysis; energy transition; energy efficiency; behavior, and sustainable consumption; energy poverty, access, and justice; big data and AI for clean energy; limitations of models; and other emerging topics for the energy systems; and real world energy assignments. Other key words: energy system analysis, energy course, energy class, open course."
  navbar:
    background: light
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Lectures
        href: lectures.qmd
      - text: Assignments
        href: assignments.qmd    
      - text: Project
        href: project.qmd
      - text: Resources
        href: resources.qmd
      - text: Dr. Gang He
        href: http://drganghe.github.io        
    right: 
      - icon: github
        href: https://github.com/drganghe/est603-energy-systems-analysis-2022-fall
  page-navigation: true
  page-footer: 
    left: "&copy; 2022 [Gang He](http://drganghe.github.io)" 
    right: 
      - icon: github
        href: https://github.com/drganghe/est603-energy-systems-analysis-2022-fall
      - icon: twitter 
        href: https://twitter.com/DrGangHe
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/drganghe/est603-energy-systems-analysis-2022-fall
  repo-actions: [edit, issue, source]
  open-graph: true
  twitter-card: true
  #  creator: "@DrGangHe"
  #  image: "/lectures/lecture2/images/boe-equations.png"
  site-url: "https://drganghe.github.io/est603-energy-systems-analysis-2022-fall"
  google-analytics:
    tracking-id: "G-X3EWB1872J"
    anonymize-ip: true

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'

comments:
  hypothesis: false
  

