---
title: Course Schedule
---

| Week | Date  | Lecture                                                              | Assignment                                                               |
|-----------------|-----------------|---------------------|-----------------|
| 1    | 8/22  | [Introduction](lectures/lecture1/index.qmd)                          | [HW0](assignments/hw0.qmd)                                               |
| 2    | 8/29  | [Make sense of energy numbers](lectures/lecture2/index.qmd)          | [HW1](assignments/hw1.qmd) assigned                                      |
| 3    | 9/5   | [Energy systems overview](lectures/lecture3/index.qmd)               |                                                                          |
| 4    | 9/12  | [Economics for energy systems analysis](lectures/lecture4/index.qmd) | [HW1](assignments/hw1.qmd) due </br> [HW2](assignments/hw2.qmd) assigned |
| 5    | 9/19  | [Energy sources](lectures/lecture5/index.qmd)                        |                                                                          |
| 6    | 9/26  | [Energy demand](lectures/lecture6/index.qmd)                         | [HW2](assignments/hw2.qmd) due                                           |
| 7    | 10/3  | [Energy, environment, and health](lectures/lecture7/index.qmd)       | [HW3](assignments/hw3.qmd) assigned                                      |
| 8    | 10/10 | Fall Break -- No class in session                                    |                                                                          |
| 9    | 10/17 | [Energy and climate change](lectures/lecture8/index.qmd)             |                                                                          |
| 10   | 10/24 | [Power sector analysis](lectures/lecture9/index.qmd)                        | [HW3](assignments/hw3.qmd) due                                           |
| 11   | 10/31 | [Energy transition](lectures/lecture10/index.qmd)          | Proposal due                                                             |
| 12   | 11/7  | [Energy efficiency, behavior, and sustainable consumption](lectures/lecture11/index.qmd)          |                                                                          |
| 13   | 11/14 | Energy poverty, access, and justice                                      | 4                                                                        |
| 14   | 11/21 | Big data and AI for clean energy \[Thanksgiving Week\]               |                                                                          |
| 15   | 11/28 | Limitations of models                                                |                                                                          |
| 16   | 12/5  | No class -- preparing final paper                                    | Presentation due                                                         |
| 17   | 12/12 | No class -- preparing final paper                                    | Paper due                                                                |
