---
title: Homework 3 Energy technology and impacts
aliases:
  - /homeworks/hw3.html
#draft: true
format: 
  html: 
    theme: cosmo
 #   css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
---

## 1. Learning rates

[Renewable costs](https://ourworldindata.org/cheap-renewables-growth) have declined drastically in the past decade. Learning curve describles the emperical relationship between unit costs and cumulative production/installation. Please use the learning curve model to calculate the learning rates of onshore wind and utility scale solar PV in the U.S. and project future prices/capacities. 

Lawrence Berkeley National Laboratory reports wind and solar data in the U.S. The most recent ones are the [Land-Based Wind Market Report 2022](https://emp.lbl.gov/wind-technologies-market-report) and [Utility-Scale Solar, 2022 Edition](https://emp.lbl.gov/utility-scale-solar). 

Use the [data](data/hw3-1data.xlsx) for 2010-2021 (higlighted in red) extracted from the reports:
 
1. Calculate the learning rates of onshore wind (0.5pt) and utility scale solar PV (0.5pt) in the U.S.\  
2. Then use your findings to project the future of wind and solar projects in the U.S. by 2030.\  
  - If U.S. wants to achieve the \$700(2021USD)/kW cost goal by 2030 (see [ATB](https://atb.nrel.gov/electricity/2022/index) forecast), how much more wind capacity should U.S. target to intall from 2022 to 2030?  (0.5pt)\
  - Assume U.S. can achieve a 500GW cumulative utility scale solar PV by 2030, what will be the unit cost of solar PV in 2030? (0.5pt)\ 
3. Discuss the drivers and uncertainties of learning curve, and show if your projections make sense. (1pt)

Please show your formula, data, and results, draw a learning curve and discuss merits and limitation of the learning curve. 


## 2. Offshore wind technology

The U.S. has a goal to have 30GW offshore wind by 2030, and New York is at the frontier of reaching 9GW by 2035. Assume you are the project manager representing your commpany, an offshore wind developer, to bid in New York's [2022 offshore wind solicitation](https://www.nyserda.ny.gov/All-Programs/Offshore-Wind/Focus-Areas/Offshore-Wind-Solicitations/2022-Solicitation). Use the skills you learned from the class to prepare your bid.

1. Resources are key for project success. If you know the average wind speed of solicitation site is 8.18m/s. Can you use the average wind speed to estimate the capacity factor, assuming the wind turbines can achieve rated power at the wind speed of 12m/s. (0.5pt)\
2. Now download the [hourly wind speed](data/hw3-2wind.csv) from [Renewables Ninja](https://www.renewables.ninja/) using the longitude and lattitude of the solicitation site. Compute the annual average capacity factor using hourly wind speed, or simulated hourly capacity factor.(0.5pt)\
3. Your CEO needs to know the LCOE of the proposed project in order to make an investment decision. As a reference, the 2.5 GW Empire Wind Offshore along with Beacon Wind receives a power purchase agreement at $80.40/MWh. Assume your company will bid for the 2GW capacity project. Try to search other information you need to figure out the LCOE and learn if it make sense for your company to bid and what price should you offer? Note your answer will depends on your reasonable assumptions. (2pt)


## 3. How much land does it really need for solar to power the U.S. and the world

You may see [news or analysis](https://landartgenerator.org/blagi/archives/127) that a small portion of U.S. (or the world's) land can power the electricity need for the U.S. (or the whole world). With the class, you should feel uneasy not to do some back-of-the-envelope calculations to check if those claims really make sense. 

1. First, go to credible sources to get the basics: total electricity consumpiton in the U.S (world) in 2021, average capacity factor of solar PV in the U.S. (world) in 2021 (if you do not have the direct number, you can use the total solar generation and total solar capacity to calculate the capacity factor). Please show your number and sources, it is also good practice to compare multiple sources. (0.5pt)\
2. Next, figure out how much solar capacity is needed to meet the electricity demand for both the U.S. and the world if all powered by solar. (0.5pt)\
3. In addition, get the land use intensity of solar PV, citing [NREL](https://www.nrel.gov/analysis/tech-size.html) report or other research papers, you may get a range of numbers and you can calculate the results as a range. (1pt)\
4. Now, you can calculate how much land is needed to power U.S. and the whole world. (0.5pt)\
5. Compare your results with what you read from the news, and the total area of Long Island, and the area of the New York State.  (0.5pt)\
6. Discuss what factors will impact your results, and how to interpret your results. (1pt)

Further reading: @yelle_learning_1979, @cagle2022standardized, @loveringa2022land

### References

::: {#refs}
:::
